source 'https://github.com/facetec/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'BlinkingLabel' do
    pod 'BlinkingLabel'
    pod 'ZoomAuthentication'
end





































use_frameworks!

target 'BlinkingLabel_Example' do
    #pod 'BlinkingLabel', :path => '../'
  pod 'Alamofire', '~> 4.7'
  # pod 'ZoomAuthentication', :git => 'https://github.com/facetec/cocoapods-specs.git'
  # pod 'ZoomAuthentication','~> 6.2.2'
end

use_frameworks!

#target 'BlinkingLabel_Example' do
#     pod 'Alamofire', '~> 4.7'
#end

#  target 'BlinkingLabel_Tests' do
#      #    inherit! :search_paths
##    use_frameworks!
#    pod 'BlinkingLabel', :path => '../'
#end
#
target 'BlinkingLabel_Tests' do
    inherit! :search_paths
      pod 'Alamofire', '~> 4.7'
    # pod 'Alamofire', '~> 4.7'
#    pod 'ZoomAuthentication', :git => 'https://github.com/facetec/cocoapods-specs.git'
# pod 'ZoomAuthentication','~> 6.2.2'
##
end
