source 'https://github.com/CocoaPods/specs.git'
source 'https://github.com/facetec/cocoapods-specs.git'
platform :ios, '10.0'

use_frameworks!

target 'BlinkingLabel_Example' do
  pod 'BlinkingLabel', :path => '../'
  # pod 'Alamofire', '~> 4.7'
  pod 'ZoomAuthentication', :git => 'https://github.com/facetec/cocoapods-specs.git'
  # pod 'ZoomAuthentication','~> 6.2.2'
end

#  target 'BlinkingLabel_Tests' do
#    inherit! :search_paths
#    pod 'Alamofire', '~> 4.7'
##    pod 'ZoomAuthentication', :git => 'https://github.com/facetec/cocoapods-specs.git'
##    pod 'ZoomAuthentication','~> 6.2.3'
#
#end
